# Video Quality Settings
vo=gpu-next
profile=high-quality
hwdec=auto-safe

# Complete Borderless Minimalism
border=no
osc=no

# Subtitles
sub-auto=fuzzy
sub-font="Outfit"
sub-font-size=44
sub-bold=yes

# Shaders (Anime4K Real-time Upscaling & Restoration)
# '~~/' prefix resolves dynamically to this isolated config directory at runtime
glsl-shaders="~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl;~~/shaders/Anime4K_Auto_Restore_VL.glsl"
