query ($id: Int, $type: MediaType) {
  Media(id: $id, type: $type) {
    characters {
      nodes {
        id
        name {
          full
          native
        }
        image {
          large
        }
        description
      }
    }
  }
}
