# AniCat Vector-based Glassmorphism Theme for uosc
# Matching web UI cyan accents and deep charcoal backgrounds
foreground=00f2fe
foreground_text=ffffff
background=0d0e12
background_text=e4e4e7
active=00f2fe

# Typography and Sleek Timeline
font=Outfit
timeline_style=bar
timeline_size=32
timeline_border=1
timeline_cache=yes

# Smooth animations & layouts
volume_size=32
