#!/usr/bin/env bash
# bump-version.sh — Single source of truth for version bumps.
#
# Usage:  bash scripts/bump-version.sh 4.0.1
#         bash scripts/bump-version.sh 4.1.0
#         bash scripts/bump-version.sh 5.0.0
#
# Updates version.txt (canonical), pyproject.toml, web/package.json,
# web/src-tauri/tauri.conf.json, and flake.nix in one shot.

set -euo pipefail

NEW_VERSION="${1:-}"

if ! echo "$NEW_VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
    echo "Usage: $0 <MAJOR.MINOR.PATCH>"
    echo "  e.g. $0 4.0.1  (bug fix)"
    echo "       $0 4.1.0  (new feature)"
    echo "       $0 5.0.0  (breaking change)"
    exit 1
fi

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

# Cross-platform sed in-place: macOS uses `-i ''`, Linux uses `-i`
if [[ "$OSTYPE" == "darwin"* ]]; then
    SED_INPLACE=(sed -i '')
else
    SED_INPLACE=(sed -i)
fi

# 1. Canonical source
echo "$NEW_VERSION" > version.txt
echo "[1/6] version.txt  -> $NEW_VERSION"

# 2. pyproject.toml
"${SED_INPLACE[@]}" "s/^version = .*/version = \"$NEW_VERSION\"/" pyproject.toml
echo "[2/6] pyproject.toml  -> $NEW_VERSION"

# 3. web/package.json
node -e "
  const p = require('./web/package.json');
  p.version = '$NEW_VERSION';
  require('fs').writeFileSync('./web/package.json', JSON.stringify(p, null, 2) + '\n');
"
echo "[3/6] web/package.json  -> $NEW_VERSION"

# 4. web/src-tauri/tauri.conf.json
node -e "
  const t = require('./web/src-tauri/tauri.conf.json');
  t.version = '$NEW_VERSION';
  require('fs').writeFileSync('./web/src-tauri/tauri.conf.json', JSON.stringify(t, null, 2) + '\n');
"
echo "[4/6] web/src-tauri/tauri.conf.json  -> $NEW_VERSION"

# 5. flake.nix
"${SED_INPLACE[@]}" "s/version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"$NEW_VERSION\"/" flake.nix
echo "[5/6] flake.nix  -> $NEW_VERSION"

# 6. anicat_media/_version.py (baked into Python bytecode, no runtime file reading)
# Preserve any existing __commit__ value if present, otherwise leave empty.
EXISTING_COMMIT=""
if [ -f anicat_media/_version.py ]; then
    EXISTING_COMMIT=$(sed -n 's/^__commit__ = "\(.*\)"/\1/p' anicat_media/_version.py 2>/dev/null || echo "")
fi
cat > anicat_media/_version.py <<- PYEOF
# Auto-generated by scripts/bump-version.sh -- do not edit manually.
__version__ = "$NEW_VERSION"
__commit__ = "${EXISTING_COMMIT}"
PYEOF
echo "[6/6] anicat_media/_version.py  -> $NEW_VERSION"

echo ""
echo "All files bumped to $NEW_VERSION."
echo "Review with: git diff"
