name: CI

on:
  pull_request:
  push:


jobs:
  python-and-web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: install system dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libdbus-1-dev pkg-config

      - name: install frontend dependencies
        working-directory: web
        run: npm ci

      - name: install python dependencies
        run: uv sync --dev --all-extras

      - name: lint python
        run: uv run ruff check .

      - name: typecheck python
        run: uv run pyright

      - name: test python
        run: uv run pytest

      - name: build frontend
        working-directory: web
        run: npm run build